### PR TITLE
Set UI templates from GLib resources, rather than directly from disk.

### PR DESCRIPTION
**Pull request by mjog**
Not sure if you want to take this patch because it will break existing users.

However using GLib resources to load templates is preferential over loading them from the file system since you don't need to worry about locating templates in the file system, and the eventual "official" implementation is likely going to want to use resources as well.

### CODE REVIEW

**Comment by virtuald** [comment]
I don't know anything about GLib resources and how they work... for example, how does one specify where GLib resources are?

Does this break mywidget.py for example?

**Comment by mjog** [comment]
It would indeed break mywidget.py, because resources need to be compiled before they can be used.
1. The app's resources are defined in a `appname.gresource.xml` file
2. The resources are all compiled into a single binary using `glib-compile-resources`
3. The binary resource file is added to the executable, or in the case of Python specified once at startup

See my WIP app https://github.com/mjog/spongioblast/ for an example - resources are in the `res` directory, they are compiled using a Makefile and found at runtime by the `bin/spongioblast` application launch script.

Or see gnome-music for a more official GNOME-ish example: https://git.gnome.org/browse/gnome-music

**Comment by virtuald** [comment]
I think it's a good idea to support loading from resources. However, in an interpreted language like python, needing to recompile things before you can run your app is an impediment to quick iterative development. 

I think I would prefer to support loading from file or from resources. The most obvious way to do this would be a second keyword argument, but perhaps there's a way to just use a single argument?

**Comment by virtuald** [comment]
Also, perhaps it would make sense to create an 'examples' directory, and provide an example of each method of loading? So, move the existing example into its own directory, and copy + change it to use resources in a separate directory.

**Comment by TingPing** [comment]
If one just uses the GLib functions for opening files instead of Pythons they can get resource opening and normal file opening for free. I made a simple change to my project to use resources (files might require prepending _file://_): [gnome-gpu-info/ggi/_gi_composites.py#L64-L66](https://github.com/TingPing/gnome-gpu-info/blob/57ea049e84c6ddc2536fb9c5d1cf1288d225dafa/ggi/_gi_composites.py#L64-L66)

**Comment by mjog** [comment]
Just pushed some changes to make the example work with GResources.

@TingPing 's solution would provide backwards compatibility with existing users, just so long as they weren't specifying paths that could not be assumed to be URI's (Linux probably fine, Windows and Macs maybe problematic?), but it's still going to be incompatible with the official solution in Bug 70184.

It is a bit annoying having a compile step when using an interpreted language, I agree. However there's a lot of reasons to just take the plunge now: Going forward, bug 70184 is going to require it, GLib/GTK+ is only going to make more use of GResources in the future, and GResources are handy for other things like custom icons. Compilation is also necessary for GSettings, and serious projects are probably going to need a build tool for distribution anyway.

A simple solution like the Makefile I use above makes the amount of work involved negligible - instead of just executing `myprog.py` during development, I run `make && myprog.py` to the same effect.

**Comment by TingPing** [comment]
> Bug 70184

Where is this bug?

GResources are certainly important to modern Gtk applications and the workflow for using them with Autotools, which is the most common build system in the Gtk community, is rather simple as seen in my repo or gnome-music.

The fact my solution requires URIs like `resource://...` is rather annoying though so I'm not sure it is ideal, it was just the first thing I thought of.

**Comment by mjog** [comment]
@TingPing It's in b.g.o.: https://bugzilla.gnome.org/show_bug.cgi?id=701843

**Comment by virtuald** [comment]
Yes, serious projects will require a build system, but let's not require non-serious apps to do it too.

I can't imagine autotools is commonly used for python apps. And I don't like requiring a URI either.

I've pushed some modifications to the resource branch (see https://github.com/virtuald/pygi-composite-templates/commit/0b80fe8a2098f1094b7a4d6e82aa409e285f3b31) that will try to load from a resource first, then will try for a file path. I'm not 100% sure I like it... it is simpler, but there is always the chance that a resource path and a real path could collide. And the resulting error message could be confusing if someone were trying to load a resource.

But, I don't really like having two separate keyword arguments either.

**Comment by TingPing** [comment]
> but there is always the chance that a resource path and a real path could collide.

I think it is reasonable to assume that won't happen; Resource paths should all have a unique path usually the domain which is never a valid file path I've seen.

**Comment by virtuald** [comment]
If there are no objections to the way I implemented it, I'll merge my branch in to get this functionality and push a new release out.

**Comment by mjog** [comment]
Your approach looks good to me, but I haven't had time to test it out and might not for a while. I'd be happy if you merged it.

**Comment by virtuald** [comment]
Released as version 0.2.1

**Pull request merged**
